### ISSUE TITLE
parsing fails for files with CRLF line endings

### ISSUE THREAD

**Issue by rhelmer** [luser/rust-minidump#1]
Symbol files with a CRLF line ending don't seem to work. This happens when creating a new `Symbolizer` and use `.get_symbol_at_address()`, it also fails with the same error message if I write a unit test that uses `SymbolFile::from_file` directly:

```
thread 'sym_file::test::test_symbolfile_from_crlf_file' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to parse file"', ../src/libcore/result.rs:738
```

**Comment by rhelmer** [comment]
Looks like the problem is when https://github.com/luser/rust-minidump/blob/848e5a0e07ad39b2d83e9bc4d0c33e83f27257ff/breakpad-symbols/src/sym_file/parser.rs#L324 does a comparison against `symbol_file(&bytes)`, if I put a hacky removal of '\r' near the top of `parse_symbol_bytes` then the unit test in PR #2 passes:

```
    let mut clean = vec!();

    for byte in bytes {
        // skip carriage returns
        if *byte != 0x0d {
            clean.push(*byte);
        }
    }
```

Besides being sure there's a better way to do that in Rust, I am a bit confused about what's going wrong here.. is it that the `symbol_file` parser https://github.com/luser/rust-minidump/blob/848e5a0e07ad39b2d83e9bc4d0c33e83f27257ff/breakpad-symbols/src/sym_file/parser.rs#L314-L320 isn't accounting for `line_ending`? I can't read `nom` very well yet but that's where I'd expect it to be handled.

**Comment by luser** [comment]
Oh, this is silly:
http://rust.unhandledexpression.com/nom/fn.line_ending.html

Literally just matches "\n":
http://rust.unhandledexpression.com/src/nom/nom.rs.html#57
