### ISSUE TITLE
Teach minidump-processor to emit JSON

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#150]
This is part of the first roadmap item of https://github.com/getsentry/symbolic/issues/375 (Kill Breakpad Step 1 -- replace [minidump-stackwalk](https://github.com/mozilla-services/minidump-stackwalk)).

After some experimentation and @willkg's generous offer to teach socorro to parse whatever format we generate, I've come to the conclusion that it would indeed be cleanest to just teach minidump-processor's binary to emit JSON and then slowly upgrade it until it's at feature-parity with minidump-stackwalk.

I'm just going to add a bunch of serde `derive(Serialize)`s to the code and upgrade the command line front-end (using a similar [system to dump_syms](https://github.com/mozilla/dump_syms/blob/master/src/main.rs). For now the format will be unstable, and we'll iterate towards something everyone's happy with.

**Comment by luser** [comment]
[bug 573100](https://bugzilla.mozilla.org/show_bug.cgi?id=573100) is where this was implemented for Socorro originally.
