### ISSUE TITLE
Extract LastErrorValue from Thread TEBs

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#156]
See my implementation of this in breakpad: https://phabricator.services.mozilla.com/D107939

**Comment by luser** [comment]
> See my implementation of this in breakpad: https://phabricator.services.mozilla.com/D107939

Neat! I have an experiment on a branch in this repo that added some of the structs you need for this:
https://github.com/luser/rust-minidump/commit/4f6eae86dd16f0aaf0b6a8056989d76b691a9934

I was trying to get all the way down to the commandline arguments. Feel free to merge all or part of that branch as needed.
