### ISSUE TITLE
Support MINIDUMP_MISC_INFO_5

### ISSUE THREAD

**Issue by luser** [luser/rust-minidump#16]
This should be straightforward now given the `multi_structs` macro I wrote:
https://github.com/luser/rust-minidump/blob/e73f08c09f6177eae07f6f4f028367c61f42de1f/minidump-common/src/format.rs#L3472

**Comment by gabrielesvelto** [comment]
This is something I'll try to pick up this year and also add a way to display the XSTATE bits this introduced. We need them to better analyze certain type of crashes (such as those involving CET). I wrote a quick description of what needs to be done to implement those [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1687201#c0).
