### ISSUE TITLE
Collect Linux Standard Base Information

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#172]
In the JSON Schema this affects the following top level field:

```
"lsb_release": {                         
    "id": <string>,
    "release": <string>,
    "codename": <string>,
    "description": <string>
  },
```

No idea what this is yet.

**Comment by gabrielesvelto** [comment]
It's the version information of a Linux distro (see [here](https://searchfox.org/mozilla-central/rev/98a9257ca2847fad9a19631ac76199474516b31e/toolkit/crashreporter/breakpad-client/linux/minidump_writer/minidump_writer.cc#280-285)). It's just a file that gets written into the stream and it's a Breakpad extension. We have [some parsing code](https://github.com/mozilla-services/minidump-stackwalk/blob/main/minidump-stackwalk/stackwalker.cc#L989-L1008) for it.

**Comment by luser** [comment]
There's code [in `minidump_dump` in this repo](https://github.com/luser/rust-minidump/blob/dedd6715af3a22f5fff9c065e7c4b22c44fef320/src/bin/minidump_dump.rs#L65) to dump the raw contents of this (and the other Linux-specific streams), if you want an example of how to get the data.

**Comment by Gankra** [comment]
cpu_microcode_version is probably grouped in with this.
