### ISSUE TITLE
Retrieve Thread Names

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#173]
In the JSON Schema this affects the `threads[_].thread_name` field.

Haven't yet checked where this information is stored in the minidump.

**Comment by gabrielesvelto** [comment]
It's not, this is like the `cert_subject` field something we pull out of the .extra file so I don't think it belongs here.

**Comment by gabrielesvelto** [comment]
This also comes from the .extra file, specifically the `ThreadIdNameMapping` annotation which contains a list of thread names and TIDs. Note that on macOS it's currently borked so it only works on Windows and Linux but that's a problem in Gecko.

The code that deals with this is [here](https://github.com/mozilla-services/minidump-stackwalk/blob/9a55067a19fc1ba2cd49a39863afb2ab1723e71c/minidump-stackwalk/stackwalker.cc#L1041-L1067).

**Comment by jrmuizel** [comment]
Minidumps also now have a `ThreadNamesStream` that contains this information. It would be nice if Gecko transitioned to using `ThreadNamesStream` for broader compatibility with other tools.

**Comment by Gankra** [comment]
From minidumpapiset.h on my system:

```
typedef enum _MINIDUMP_STREAM_TYPE {
...
    ThreadNamesStream           = 24,
}

//
// The thread names stream in a minidump, containing information
// about each thread's name/description (if available).
//

typedef struct _MINIDUMP_THREAD_NAME {
    ULONG ThreadId;
    RVA64 RvaOfThreadName;
} MINIDUMP_THREAD_NAME, *PMINIDUMP_THREAD_NAME;

typedef struct _MINIDUMP_THREAD_NAME_LIST {
    ULONG NumberOfThreadNames;
    MINIDUMP_THREAD_NAME ThreadNames[0]; // Variable size buffer
} MINIDUMP_THREAD_NAME_LIST, *PMINIDUMP_THREAD_NAME_LIST;
```

**Comment by gabrielesvelto** [comment]
Interesting. I had a look too and it seems that neither breakpad nor crashpad handle these:
```
    ThreadInfoListStream        = 17,
    HandleOperationListStream   = 18,
    TokenStream                 = 19,
    JavaScriptDataStream        = 20,
    SystemMemoryInfoStream      = 21,
    ProcessVmCountersStream     = 22,
    IptTraceStream              = 23,
    ThreadNamesStream           = 24,

    ceStreamNull                = 0x8000,
    ceStreamSystemInfo          = 0x8001,
    ceStreamException           = 0x8002,
    ceStreamModuleList          = 0x8003,
    ceStreamProcessList         = 0x8004,
    ceStreamThreadList          = 0x8005, 
    ceStreamThreadContextList   = 0x8006,
    ceStreamThreadCallStackList = 0x8007,
    ceStreamMemoryVirtualList   = 0x8008,
    ceStreamMemoryPhysicalList  = 0x8009,
    ceStreamBucketParameters    = 0x800A,     
    ceStreamProcessModuleMap    = 0x800B,
    ceStreamDiagnosisList       = 0x800C,
```
The annotation we use for storing the thread names is a bit of a hack so if we could migrate to something standard-ish it would be a big improvement.

**Comment by gabrielesvelto** [comment]
Note that I can't find a documented way to have `MiniDumpWriteDump()` populate those streams (and specifically `ThreadNamesStream`) but given that the format is documented we could do it ourselves in our writers :-).

**Comment by Gankra** [comment]
Some googling suggests it will use the value of [SetThreadDescription](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription?redirectedfrom=MSDN).

**Comment by Gankra** [comment]
...which we use, so we have thread names!
