### ISSUE TITLE
Support Mozilla's "extra" json file?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#177]
Breakpad completely controls the minidump format on linux/macos, but on windows the format is completely controlled by native APIs, limiting extensibility. Mozilla hacked around this with an "extra" json file that contains:

* #173 - Thread Names
* #171 - Code Certificate Info
* #169 - Extra info for computing block stats

It's possible windows now has more proper hooks and these things can embedded in the minidump as a custom stream, similar to #175, but the path of least friction is for minidump-processor to support ingesting this file. I'm personally fine with taking that path.

I already accidentally carved out an entry point for this data with the `--raw-json` flag in minidump-processor's minidump-stackwalk binary (because I just copied its interface). Look for `raw_root` in [this file](https://github.com/mozilla-services/minidump-stackwalk/blob/main/minidump-stackwalk/stackwalker.cc) for how Mozilla currently uses it.

**Comment by luser** [comment]
Crashpad has [its own minidump stream for annotations like this](https://github.com/luser/rust-minidump/blob/bd19df3fc6dc927aca1197fab33736f41ba12ed2/minidump-common/src/format.rs#L2006) which is conveniently already supported by this crate.  It might be good to look at whether Firefox can reuse that at some point.

In the near-term, I guess the right thing to ask is: do you expect Socorro to use the `minidump_stackwalk` binary from this crate right out of the box, or should it have its own binary that uses this as a library? I don't have strong opinions either way, but doing the latter (you could put the Rust project in [the existing minidump-stackwalk repo](https://github.com/mozilla-services/minidump-stackwalk/)) would mean less hassle for making your changes and tweaking the binary to work exactly the way you want it. @willkg: what do you think?

**Comment by willkg** [comment]
I'm game for that. It's effectively a continuation of the existing situation.

**Comment by Gankra** [comment]
With thread names being handled properly, this file is a lot less appealing.

**Comment by gabrielesvelto** [comment]
It never has been particularly appealing (and it used to be INI-format to boot!) but we didn't have a simple way to add extra information to the minidump. Keep in mind that this design dates back at least 15 years. If we'd move crash annotations into the minidump we could possibly get rid of it but the changes in Gecko are non-trivial and would have to be platform-specific because of Windows writing its own minidumps.

**Comment by gabrielesvelto** [comment]
That's to say: we still need it for the crash annotations for the time being but I'm game for folding its contents into the minidump once everything else is in place.
