### ISSUE TITLE
minidump processor should fill os_version, cpu_info fields in SystemInfo

### ISSUE THREAD

**Issue by luser** [luser/rust-minidump#19]
This would get populated here:
https://github.com/luser/rust-minidump/blob/e73f08c09f6177eae07f6f4f028367c61f42de1f/minidump-processor/src/processor.rs#L108

There are commented-out tests here:
https://github.com/luser/rust-minidump/blob/e73f08c09f6177eae07f6f4f028367c61f42de1f/minidump-processor/tests/test_processor.rs#L55

**Comment by Gankra** [comment]
Gonna also lump cpu_microcode_version in with this

**Comment by Gankra** [comment]
Actually scratch that, it's a linux /proc/cpuinfo thing
