### ISSUE TITLE
Make CFI unwinders forward callee-saved registers by default

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#196]
It seems that if a callee-saved register hasn't been modified, the STACK CFI (and STACK WIN?) directives just won't mention it, and we should forward it. This is probably why `.undef` exists as a value?

I think the right solution would be to clone the callee's registers into the StackWalker's caller registers and set all of the callee-saved registers to valid for the caller. Then walker.rs can clear a register in the case of `.undef` or an evaluation error..?

**Comment by luser** [comment]
The Breakpad implementation was not very concerned with registers that weren't directly related to stack unwinding. If it's straightforward I don't see any reason not to recover as many registers as possible.
