### ISSUE TITLE
Migrate over way more stackwalker tests from breakpad

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#197]
This is a big tedious task, but important for improving implementation robustness.

Breakpad has several tests in `src/processor/stackwalker_*_unittest.cc`. e.g.

https://github.com/google/breakpad/blob/main/src/processor/stackwalker_amd64_unittest.cc

Our tests in `minidump-processor/src/stackwalker/*_unittest.rs` are replicating those tests. In the ARM64 unwinder I have introduced the ability to [test cfi](https://github.com/luser/rust-minidump/blob/master/minidump-processor/src/stackwalker/arm64_unittest.rs#L397). I'm not sure if that should just be copy-pasted or pulled out to some common framework (probably the former, but the latter might be better for migrating to symbolic..?).

Part of me just wants these tests to be written in a declarative format like

```
stack: 0aef23...
context: { rax: 0x0, rbx: 0x08, ... }
module: { ... }
cfi: { ... }
expected: [
  { 
    trust: context, 
    registers: { rax:  0x0, rbx: 0x08 ... }
  }
]
```

But that's probably over-engineering...

**Comment by luser** [comment]
Feel free to write ridiculous macros to make declarative tests. :) That's the one use case for which I wholeheartedly endorse Rust macros.
