### ISSUE TITLE
Make minidump_dump print out the memory info list

### ISSUE THREAD

**Issue by gabrielesvelto** [luser/rust-minidump#234]
minidump_dump should print out the entries in the minidump memory info list like breakpad does. See [this](https://searchfox.org/mozilla-central/rev/55e8eba74b60b92d04b781f7928f54ef76b13fa9/toolkit/crashreporter/google-breakpad/src/processor/minidump.cc#4771-4788) and [this](https://searchfox.org/mozilla-central/rev/55e8eba74b60b92d04b781f7928f54ef76b13fa9/toolkit/crashreporter/google-breakpad/src/processor/minidump.cc#4584-4601)

**Comment by Gankra** [comment]
Fixed by #264
