### ISSUE TITLE
Implement stack unwinding for more architectures, use unwind info, stack scanning

### ISSUE THREAD

**Issue by luser** [luser/rust-minidump#26]
Currently we only have support for unwinding stacks on x86:
https://github.com/luser/rust-minidump/blob/e73f08c09f6177eae07f6f4f028367c61f42de1f/minidump-processor/src/stackwalker/mod.rs#L19

and even on x86 we only support unwinding with frame pointers:
https://github.com/luser/rust-minidump/blob/e73f08c09f6177eae07f6f4f028367c61f42de1f/minidump-processor/src/stackwalker/x86.rs#L81

We should at least support unwinding the CPU architectures that Firefox ships on (x86-64, arm, aarch64). Additionally, we should support using unwind info from symbol files (`STACK CFI` and `STACK WIN`) to unwind, since those produce more useful results when available. Finally, we should support stack scanning like Breakpad does so we can get fuller stacks when traditional unwinding fails.

Ideally we'd figure out how to share unwind code with other projects, but in the short term simply porting Breakpad's unwind code would be sufficient to make this useful.

**Comment by Gankra** [comment]
Closing this in favour of smaller more focused issues above ^
