### ISSUE TITLE
minidump_dump doesn't handle windows thread stack RVA bug

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#265]
I noticed this problem and fixed it in minidump-processor, but forgot about minidump_dump (because I never use it and don't especially understand its purpose). This was annoying when I wanted dumps of stack memory and remembered minidump_dump is supposed to do that!

Unfortunately it can't because of this issue. It's annoying to fix at the level of stream parsing because you need to pull up the MemoryStream to do a proper by-address-lookup. The easy direct fix is to make MinidumpThreadList::print (optionally?) take a MemoryStream so that it can fix up the stack memory too.

Alternatively you could give MinidumpThreadList a `fix_stacks` method that takes the MemoryStream and fixes every thread's stack (and then minidump-processor and minidump-dump can both just invoke that).

https://github.com/luser/rust-minidump/blob/b75c795348c23e195b7eee953c323df993916e15/minidump/src/minidump.rs#L1579-L1587

https://github.com/luser/rust-minidump/blob/b75c795348c23e195b7eee953c323df993916e15/minidump-processor/src/processor.rs#L192-L199

**Comment by gabrielesvelto** [comment]
minidump_dump is mostly used when you're dealing with incomplete, corrupted or odd minidumps and you just want to see the raw data in the various streams, no questions asked.

**Comment by Gankra** [comment]
I'm not sure if that's for or against fixing this "bug".

**Comment by Gankra** [comment]
Fixed by #289
