### ISSUE TITLE
Expose the raw iterator for key-value linux streams?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#273]
A bunch of linux streams are just a bunch of string key-value pairs. Right now we just pick out a few interesting values, stuff them in a struct, and call it a day. But it would probably be more useful to expose the raw key-value iterator so that users can scan the list and pull out other values on demand.

This requires a bit more thinking about my current unquoting scheme. Maybe expose versions with and without the unquoting stuff? Not sure if there are situations where `trim`ing the values would be inappropriate.

Also not sure if the current iterator impls would have weird lifetime problems. Certainly all those streams would need to have a `'mdmp` lifetime to be able to create the iterator on demand.

At that point I guess you could also expose the raw byte buffer too.

**Comment by luser** [comment]
I'd probably hold off on overdesigning the API until you find yourself needing something more than what you have. There's already API surface to get raw stream contents as bytes, which is an OK fallback position for these simple types of streams.

**Comment by Gankra** [comment]
Fixed by #275
