### ISSUE TITLE
diagreement on last_error_value

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#290]
```
socc-pair --crash-id=72255e8d-efc7-4726-b655-0ccbc0211110
```

```diff
-      did not match
+      last_error_value: STATUS_WAIT_3
-      last_error_value: ERROR_PATH_NOT_FOUND
```

I expect this is because we inverted the order of NtStatus and WinError in #286, and this is fine, but filing just in case.

cc @gabrielesvelto

**Comment by Gankra** [comment]
This dump also includes an incredibly rare actual-null-from-socorro in the unloaded_modules:

```diff
-    completely different types for 2:
+
       2: null
-
       2: {
         base_addr: 0x72540000
         cert_subject: null
         code_id: 56F584F44000
         end_addr: 0x72544000
         filename: KBDRU.DLL
       }
```

**Comment by gabrielesvelto** [comment]
I suspect that in this particular case `STATUS_WAIT_3` is the correct answer given we're in a waiting function... but it's an edge case and we don't care; our goal is to catch all errors, a false positive here and there won't matter. A false negative would on the other hand.

**Comment by Gankra** [comment]
SGTM
