### ISSUE TITLE
double unloaded module weirdness on x86 windows?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#291]
socc-pair --crash-id=72255e8d-efc7-4726-b655-0ccbc0211110

This dump includes a curiousity in unloaded_modules:

```diff
     1: {
       base_addr: 0x72540000
       code_id: 50F322EB4000
       end_addr: 0x72544000
       filename: api-ms-win-downlevel-shell32-l1
     }
-    completely different types for 2:
+
       2: null
-
       2: {
         base_addr: 0x72540000
         cert_subject: null
         code_id: 56F584F44000
         end_addr: 0x72544000
         filename: KBDRU.DLL
       }
```

This is a bit weird. It seems like there's two different unloaded modules claiming the same address space, but with a different code_id/filename?

rust-minidump seemingly reports both, while breakpad only includes one? I'm not totally clear on if this "null" is real or just an artifact of the processing socc-pair does on the two module lists to treat them as unordered sets (since socc-pair and rust-minidump do not present them in the same order, for whatever reason).

Filing now, will look at closer later.

**Comment by gabrielesvelto** [comment]
I've seen something like this happen in other minidumps and I think it means that the first module was loaded, then unloaded, then a new one was loaded in the room that had been emptied, then unloaded again. It is my understanding that the list of unloaded modules is not a snapshot of the modules that have been unloaded at a certain point but rather the history of all modules that have been unloaded. As such it might be possible to find two or more entries of the same module too if it was loaded and unloaded more than once.

**Comment by Gankra** [comment]
Confirmed: socorro is just dropping this unloaded module on the floor, so this is a nice example of us doing strictly better 🎊
