### ISSUE TITLE
panicked at 'overlapping ranges 2263992 -- 2359295 and 2267536

### ISSUE THREAD

**Issue by hiikezoe** [luser/rust-minidump#30]
When I run [chkimg](https://github.com/heycam/chkimg) for https://crash-stats.mozilla.com/report/index/00baec0f-e306-4301-a4f2-8b2700180919, it causes the panic.

   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: <range_map::RangeMap<T, V>>::normalize
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/minidump-0.1.0/<panic macros>:8
   8: <range_map::RangeMap<T, V>>::from_sorted_vec
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/range-map-0.1.5/src/lib.rs:161
   9: <range_map::RangeMap<T, V> as core::iter::traits::FromIterator<(range_map::Range<T>, V)>>::from_iter
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/range-map-0.1.5/src/lib.rs:143
  10: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1419
  11: minidump::minidump::MinidumpMemoryList::from_regions
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/minidump-0.1.0/src/minidump.rs:827
  12: <minidump::minidump::MinidumpMemoryList as minidump::minidump::MinidumpStream>::read
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/minidump-0.1.0/src/minidump.rs:880
  13: minidump::minidump::Minidump::get_stream
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/minidump-0.1.0/src/minidump.rs:1300
  14: chkimg::run
             at src/main.rs:356

**Comment by luser** [comment]
This is basically the same issue as https://github.com/luser/rust-minidump/issues/24 . I wrote up an explanation there. We'll need to either fix the range-map crate we're using or find something else to use.

**Comment by luser** [comment]
This should be fixed in https://github.com/luser/rust-minidump/commit/f145ae42070c70e3043afbc4b3fb9be16180a153
