### ISSUE TITLE
Figure out minidump-tools

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#305]
Up to this point I've completely avoided understanding what minidump-tools is. I just pop in there and fixup code when I change an API and run away. It has no README, it has no docs. All I know is it's a weird library with some micro-binaries wrapping it.

I think whatever it's trying to do is almost certainly better handled by improving minidump-stackwalk or minidump-dump. If we conclude otherwise, then it needs some work to be able to publish it properly. We would need separate top-level crates for each binary, and we need to do something about the unconditional dependency on https://github.com/luser/rust-disasm, which makes Cargo reject publishing it at all.

If we determine it doesn't do anything we care about, we should just delete it and remove the maintenance burden.

**Comment by luser** [comment]
It's where I stuck Rust ports of the random tools I accumulated over the years for poking at minidumps:
https://hg.mozilla.org/users/tmielczarek_mozilla.com/

They could be spun out into separate repos. They're only here because it was convenient at the time.
