### ISSUE TITLE
Remove total_frames and frames_truncated

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#317]
I just remembered these exist:

https://github.com/luser/rust-minidump/blob/a224c912df9ddde3a956f9796176b3aacde69b1a/minidump-processor/src/process_state.rs#L686-L689

They're legacy cruft from an anti-feature of the old minidump-stackwalk. We disabled it long ago because it was confusing people to have truncated backtraces, so these fields never contain any signal. I doubt socorro looks at them.

Note that frame_count would still exist.

cc @willkg

**Comment by willkg** [comment]
Bug for removing these from Socorro: https://bugzilla.mozilla.org/show_bug.cgi?id=1743487
