### ISSUE TITLE
Do not make unbounded memory reserves based on untrusted inputs

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#326]
This is apparently an issue Sentry ran into when testing this library out. We would blow up their allocator guards against enormous allocations. The specific case we discussed involved the count of streams in the directory, which was larger than the file size could even hold.

There are a few options here:

1. Do not reserve but otherwise go along with the count
   * Optionally: also iterate the list backwards so overflows will fast-fail
2. Have a (static?) `max` on the reserve size
3. Have a (static?) `max` on the counts (e.g. declare that we refuse to acknowledge the validity of a minidump with 1000+ streams)
4. Reserve, but check that the count is physically possible (in terms of the input buffer size and size of the entries)

I am personally inclined to take the braindead simple approach of Option 1.

Here's the offending cases:

```
> rg "with_capacity|reserve\(|reserve_exact\("
minidump-common\src\traits.rs
79:        let mut vec: Vec<(Range<u64>, V)> = Vec::with_capacity(input.len());

minidump\src\minidump.rs
1122:    let mut raw_entries = Vec::with_capacity(count);
1194:    let mut raw_entries = Vec::with_capacity(number_of_entries as usize);
1212:        let mut names = HashMap::with_capacity(raw_names.len());
1350:        let mut modules = Vec::with_capacity(raw_modules.len());
1443:        let mut modules = Vec::with_capacity(raw_modules.len());
1620:        let mut regions = Vec::with_capacity(descriptors.len());
2315:        let mut threads = Vec::with_capacity(raw_threads.len());
2316:        let mut thread_ids = HashMap::with_capacity(raw_threads.len());
3902:    let mut strings = Vec::with_capacity(count as usize);
4040:    let mut module_links = Vec::with_capacity(count as usize);
4218:        let mut streams = HashMap::with_capacity(header.stream_count as usize);
```

Those that key off `len()` are fine because they're all based on a collection we've already constructed.

Filtering that down we get:

```
minidump\src\minidump.rs
1122:    let mut raw_entries = Vec::with_capacity(count);
1194:    let mut raw_entries = Vec::with_capacity(number_of_entries as usize);
3902:    let mut strings = Vec::with_capacity(count as usize);
4040:    let mut module_links = Vec::with_capacity(count as usize);
4218:        let mut streams = HashMap::with_capacity(header.stream_count as usize);
```

**Comment by luser** [comment]
Oof, yeah. Rust still doesn't have fallible memory allocation yet, does it? Thanks for auditing the code to find all those other callsites!

`read_stream_list` has sensibly-paranoid code for validating the count of items, we should do the same work anywhere we read a count from the file data:
https://github.com/luser/rust-minidump/blob/13463d07c32113bc060c8b2094b13db282a1cba1/minidump/src/minidump.rs#L1095-L1107

You could probably make that a generic method if desired, since `read_stream_list` itself is already generic over types that `#[derive(Pread)]`. Something like:

```rust
fn validate_array_size<'a, T>(
    entries_count: usize,
    bytes: &'a [u8],
    endian: scroll::Endian,
) -> bool
where
    T: TryFromCtx<'a, scroll::Endian, [u8], Error = scroll::Error>,
    T: SizeWith<scroll::Endian>,
{
}
```

Aside from using checked arithmetic (for extra caution), it checks that the expected size of the resulting array of data fits in the bytes available, which is a very sensible upper bound. I'm sure Sentry has size limits on the minidump files they accept from clients like crash-stats does, so "we won't ever allocate an order of magnitude more memory than the byte length of the minidump file" should ensure that we don't go off the rails.

**Comment by Gankra** [comment]
try_reserve was actually [just stablized](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#fallible-allocation) but I'm not sure that's the right solution regardless.

**Comment by willkg** [comment]
I think processing this crash report died because of this issue:

https://crash-stats.allizom.org/report/index/cea2d009-a1af-4964-bd1b-9cad90211213

The stderr is:

```
memory allocation of 268435456 bytes failed
```

If it isn't related to this issue, I can write up a new issue for it.

**Comment by Gankra** [comment]
The minidump doesn't seem particularly weird, from my cursory investigation.

The failing allocation is "only" a 268mb allocation, and libxul is 194mb here. That allocation size would make sense if the code that downloads it isn't trusting it to have a particular size and is doing normal exponential resizing (268435456 is 0b10000000000000000000000000000, exactly a power of two).

It's... *mildly* concerning that we're doing this kind of reallocation on symbol files, but I don't know enough about networking code to know if that's like Standard or not. It's possible the async branch (#329) fixes this, since it stays more natively in reqwest types.

But anyway, iirc we regularly download and handle 1GB symbol libxul files, so this seems like a "normal" OOM from an overloaded node. Was breakpad more resilient to OOM?

**Comment by willkg** [comment]
Whether Breakpad stackwalker did this or was more/less resilient, I'm not sure. However, the "percent used" memory graphs for stage (running rust-minidump minidump-stackwalk) spike more than prod (breakpad stackwalker).

Here's a spike in stage over the last 6 hours:

![image](https://user-images.githubusercontent.com/820826/145831694-960bb5bf-713d-463e-a377-6e66623597de.png)

Prod hovers between 20% and 40% and doesn't spike.

Sounds like this is a different issue, so I'll write up a separate issue for it. Also, I'll write up a Socorro bug to look at memory on the processor nodes.
