### ISSUE TITLE
curiosity 2: crashing_thread thread_index vs. threads_index

### ISSUE THREAD

**Issue by willkg** [luser/rust-minidump#331]
minidump-stackwalk: minidump-stackwalk 0.9.4 (2021-11-30 5069ee3)

breakpad stackwalker emits "crashing_thread.threads_index".

minidump-stackwalk emits "crashing_thread.thread_index".

Given that this is the index into the "threads" list, I think minidump-stackwalk should change to "threads_index".

**Comment by Gankra** [comment]
Oops!

**Comment by willkg** [comment]
I should have seen this aaaaaaages ago. Sorry about that!
