### ISSUE TITLE
curiosity 3: unloaded modules emitted multiple times

### ISSUE THREAD

**Issue by willkg** [luser/rust-minidump#332]
minidump-stackwalk: minidump-stackwalk 0.9.4 (2021-11-30 5069ee3)

crash report: d770f564-94fd-4c12-8c24-7ef870211203

stage (minidump-stackwalk): https://crash-stats.allizom.org/report/index/d770f564-94fd-4c12-8c24-7ef870211203#tab-rawdump

This module is emitted many many times:

```
{
    "base_addr": "0x61cb0000",
    "cert_subject": null,
    "code_id": "5005DCDE27000",
    "end_addr": "0x61cd7000",
    "filename": "WLIDNSP.DLL"
},
```

prod (stackwalker): https://crash-stats.mozilla.org/report/index/d770f564-94fd-4c12-8c24-7ef870211203#tab-rawdump

breakpad only emits it once.

**Comment by Gankra** [comment]
Ah interesting, socc-pair probably doesn't notice this since it [compares the modules by name using a HashMap](https://github.com/Gankra/socc-pair/blob/main/src/main.rs#L729-L741), so duplicates get silently dropped.

I believe `stackwalker` also sorts the modules by address, so it's possible deduping happens there? That or I have a nasty bug! Investigating...

**Comment by willkg** [comment]
Some more examples:

* 3c370128-91d8-4371-ac70-fa0d10211203
* 456fc5dd-cff4-466f-86c7-17dcf0211203

**Comment by Gankra** [comment]
3c370128-91d8-4371-ac70-fa0d10211203 is interesting because the addresses of Rstrtmgr.dll actually changes, suggesting this is not simply purely duplicated data:

```
{

    "base_addr": "0x75580000",
    "cert_subject": null,
    "code_id": "4A5BDA7938000",
    "end_addr": "0x755b8000",
    "filename": "ncrypt.dll"

},
-
{

    "base_addr": "0x71300000",
    "cert_subject": null,
    "code_id": "4A5BDAE328000",
    "end_addr": "0x71328000",
    "filename": "Rstrtmgr.dll"

},
-
{

    "base_addr": "0x75580000",
    "cert_subject": null,
    "code_id": "4A5BDA7938000",
    "end_addr": "0x755b8000",
    "filename": "ncrypt.dll"

},
-
{

    "base_addr": "0x712d0000",
    "cert_subject": null,
    "code_id": "4A5BDAE328000",
    "end_addr": "0x712f8000",
    "filename": "Rstrtmgr.dll"

}
```

**Comment by Gankra** [comment]
I've sent an email to microsoft asking them a few different questions about the significance of ordering/duplication.

**Comment by Gankra** [comment]
> As for the unloaded module list, this seems to come from: RtlGetUnloadEventTraceEx function - Win32 apps | Microsoft Docs

 

> From a quick look at the code for the loader, it seems that each entry in that list corresponds to a single module unload event, but it is a circular list with a limited number of elements.  So you could get duplicates at the same address or at different addresses based on where the loader decides to place a module each time it is loaded. So they are technically in unload order, but since it’s a circular list I don’t think there’s any indication on where the “start” of the list is.

**Comment by Gankra** [comment]
So the duplicates and order does represent a signal, but it's a messy signal. I think it's probably "better" to keep them around as More Information but feel free to disagree.

**Comment by willkg** [comment]
I think what you're getting at is "let's keep it the way it's implemented for now". Does that sound right?

If so, that's cool. I'll look into whether I have to make changes in Crash Stats on Monday.

**Comment by Gankra** [comment]
Yeah i think there's useful signal in the dupes, but i need to clarify the
docs.

**Comment by gabrielesvelto** [comment]
> > As for the unloaded module list, this seems to come from: RtlGetUnloadEventTraceEx function - Win32 apps | Microsoft Docs
> 
> > From a quick look at the code for the loader, it seems that each entry in that list corresponds to a single module unload event, but it is a circular list with a limited number of elements.  So you could get duplicates at the same address or at different addresses based on where the loader decides to place a module each time it is loaded. So they are technically in unload order, but since it’s a circular list I don’t think there’s any indication on where the “start” of the list is.

This is very good to know. We've considered using this list to validate pointers that jump into nothingness, something we've seen with injected DLLs crashing us but then unloading themselves before we could get them in the act. If there can be multiple mappings at the same addresses and there's no guarantee of the order in which they happened then we should probably discard this idea. Or maybe we could do it but only when we have only one unload event covering a certain address range but discard potentially ambiguous situations where more than one unloaded mapping covers the same area.

**Comment by Gankra** [comment]
sounds like another wontfix
