### ISSUE TITLE
RangeMap isn't the right abstraction for UnloadedModules

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#334]
I either didn't care or forgot about it when I filled in the implementation by copy-pasting the Modules stream.

UnloadedModules can necessarily overlap by address, so they need to be treated more like MultiSets rather than Sets.

This suggests changes to `by_addr` and `module_at_address`. by_addr can be changed in the implementation, but module_at_address needs a signature change to express the fact that it's a multi-set. Maybe return an iterator?

**Comment by Gankra** [comment]
Currently not a real issue because we only use the normal `iter` which doesn't use the RangeMap. But this affects e.g. the proposals in #168.

**Comment by gabrielesvelto** [comment]
Returning an iterator SGTM
