### ISSUE TITLE
use error codes in stderr for processing errors

### ISSUE THREAD

**Issue by willkg** [luser/rust-minidump#354]
When minidump-stackwalk processes [ca472b14-67b6-4e00-a272-52f7c0211208])http://localhost:8000/report/index/ca472b14-67b6-4e00-a272-52f7c0211208?refresh=cache), it doesn't produce any JSON output, so there's no "status" field. Turns out Socorro's crash signature generation looks at that field for error codes and adds them to the signature. Fun times.

Instead of putting that data in the "status" field, minidump-stackwalk chose to spit it out to stderr. I agree that makes more sense.

However, now signatures have changed for error cases. I can adjust Socorro to look at stderr for phrases that indicate the various error situations, but the indicator text is an english sentence and someone could change that down the line breaking the Socorro processor code.

For example, minidump-stackwalk spits this out:

```
[ERROR] Error processing dump: The thread list stream was not found
```

I could look for "thread list stream was not found", but if anyone changes any of those words, the match fails and we'd never know about it.

I'd like to add error codes. So minidump-stackwalk spits out whatever, but also spits out `ERROR_NO_THREAD_LIST`. Maybe something like this:

```
[ERROR] Error processing dump: ERROR_NO_THREAD_LIST: The thread list stream was not found
```

I think it's sufficient to add error codes to this block here:

https://github.com/luser/rust-minidump/blob/6ccdead2bffb0c9db60037b1ea6923c69afba023/minidump-processor/src/processor.rs#L29-L38

Does that seem ok? Sometimes having error codes makes documentation easier. Would it help here?

**Comment by willkg** [comment]
More specifically, the signatures that changed are the ones that used to have `ERROR_NO_THREAD_LIST` and `ERROR_NO_MINIDUMP_HEADER`. I haven't seen other cases.

`ERROR_NO_MINIDUMP_HEADER` shows up when the minidump is 0-bytes. I added a check for that in the Socorro processor to shortcut the situation and not call minidump-stackwalk at all, so I'll handle that.

Thus we only really need to add `ERROR_NO_THREAD_LIST` for Socorro parity.

**Comment by Gankra** [comment]
This is reasonable. I had also considered modifying mdsw to change the return code of main to reflect the error, but the string is probably less cryptic to integrate into socorro than "oh yeah 7 means ERROR_NO_THREAD_LIST".

I will implement your proposal now.

**Comment by willkg** [comment]
Thank you!
