### ISSUE TITLE
crash address being read as 64-bit for 32-bit platforms

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#360]
socc-pair --crash-id=[082a152f-05b4-4de9-943b-c30550211210](https://crash-stats.mozilla.org/report/index/082a152f-05b4-4de9-943b-c30550211210)

```diff
 : {
   crash_info: {
-    did not match
+    address: 0xe5e5e5e5
-    address: 0xffffffffe5e5e5e5
     crashing_thread: 25
     type: EXCEPTION_ACCESS_VIOLATION_READ
   }
```

(+ is breakpad, - is rust-minidump)

This crash report is from x86, so it's almost certain that rust-minidump is wrong here.

**Comment by Gankra** [comment]
I think we need to be factoring in the Cpu in get_crash_address, but I probably need to check what breakpad does in this case:

https://github.com/luser/rust-minidump/blob/cf2031c837810b55fc813ace2a8c7fd71e8f201d/minidump/src/minidump.rs#L3746-L3759

**Comment by luser** [comment]
Looks the same:
https://chromium.googlesource.com/breakpad/breakpad/+/d93f6b93931c63704caccabb4f1a41cce8896eb1/src/processor/minidump_processor.cc#740

Is this just different integer promotion behavior in Rust vs. C++?

**Comment by Gankra** [comment]
The crash *is*  EXCEPTION_ACCESS_VIOLATION_READ, so perhaps the issue is specifically with the `self.raw.exception_record.exception_information[1]` branch, which seemingly breakpad does not include?

@gabrielesvelto I assume this is a trick you came up with?

**Comment by gabrielesvelto** [comment]
That value is sign-extended somewhere (possibly when the minidump is written out) so we were explicitly truncating it for 32-bit minidumps, see [this change](https://github.com/gabrielesvelto/minidump-stackwalk/commit/55e662c76fad3818bf401358515678bc18cd799c). Now that I look at it again it seems we were truncating all addresses for consistency.

**Comment by willkg** [comment]
That change is for this issue which explains a bit more of the context:

https://github.com/mozilla-services/minidump-stackwalk/issues/30

Having said that, I thought it specifically didn't truncate values but left those alone.

**Comment by luser** [comment]
Ohh, OK, that makes more sense! Breakpad's mdsw has [an extremely low-tech solution for this](https://chromium.googlesource.com/breakpad/breakpad/+/d93f6b93931c63704caccabb4f1a41cce8896eb1/src/processor/stackwalk_common.cc#65) for printing out register values. It doesn't do anything with the crash address, though.

My humble suggestion would be to just do:

```rust

enum Address {
  U32(u32),
  U64(u64),
}

pub fn get_crash_address(&self, system_info: &MinidumpSystemInfo) -> Address {
}
```

**Comment by Gankra** [comment]
I personally prefer everything being u64 to keep things uniform and simpl. I could certainly change json_hex and other printing code to "clean" the values, but since we have a programatic API, we should just be cleaning them at the source. So I'd just branch on Cpu::pointer_width and do a "as u32 as u64" to mask off the errant high bits.

**Comment by luser** [comment]
Oh! I see! You're already doing this, you're just not masking off 32-bit values:
https://github.com/luser/rust-minidump/blob/cf2031c837810b55fc813ace2a8c7fd71e8f201d/minidump-processor/src/process_state.rs#L836

Wouldn't a simple `val as u32` right there fix this for you?

**Comment by luser** [comment]
That's fair, but given that this is the exact value that's in the minidump it's not exactly incorrect either.

**Comment by Gankra** [comment]
> That's fair, but given that this is the exact value that's in the minidump it's not exactly incorrect either.

I totally get that urge, but in this case we're talking about bits 33+ of a Definitely 32-Bit Pointer, so I literally can't think of a situation where this could be right. But if someone does find such a case, they can always check the `raw` contents of the stream.
