### ISSUE TITLE
Infinite loop causing OOM when walking stack in `minidump-processor`

### ISSUE THREAD

**Issue by 5225225** [luser/rust-minidump#428]
On commit https://github.com/luser/rust-minidump/commit/ebbee33763b4788ef33451a98fd4ecb90ebd91a3, running `cargo fuzz run process oom` (attached below in a .zip file) will infinitely loop in the following `while` statement, pushing more stuff to the `frames` vec until you eventually OOM.

https://github.com/luser/rust-minidump/blob/a32419975ba6f190081a148f04a41fc42aa4eb26/minidump-processor/src/stackwalker/mod.rs#L174-L193

[oom.zip](https://github.com/luser/rust-minidump/files/7998777/oom.zip)

Bailing out if you ever see a frame twice sounds smart.

Are instruction pointers always monotonically increasing/decreasing? If so, we can do this perfectly accurately in O(1) per frame by just checking that the instruction pointer is always increasing or decreasing by at least 1 byte per frame.

**Comment by Gankra** [comment]
We already enforce forward-progress but it appears I forgot to port the Arm fix in #309 to Arm64 and OldArm64

**Comment by Gankra** [comment]
(Arm leaf functions can genuinely not use the stack at all because the link register creates a buffer of one call where you don't even need to push a return pointer, so the unwinder needs to allow forward progress to not occur for the top of the stack, but after that it needs to be strict again)

**Comment by Gankra** [comment]
(So very good catch, this a real annoying bug we've seen in the wild!)
