### ISSUE TITLE
MinidumpModule::code_identifier: incorrect platform detection

### ISSUE THREAD

**Issue by loewenheim** [luser/rust-minidump#474]
We have seen a case in production where the check in https://github.com/luser/rust-minidump/blob/6808495b8eae53607477f0e80d843fdeacefbef4/minidump/src/minidump.rs#L931 erroneously treats a Windows minidump as MacOS for the purpose of computing the `code_identifier`. Letting it fall through to the next case returns the correct code identifier (taking breakpad as the source of truth).

**Comment by relaxolotl** [comment]
I'll try to see if I can at least take a look at the minidump and see what sort of circumstances would generate such a minidump that doesn't really conform to this rule. As far as the breakpad codebase and the (possibly outdated) MS PDB codebase is concerned this check shouldn't be wrong, but maybe crashpad actually is breaking this rule somehow.

FWIW this does help build the case that we should really be figuring out a way to access the contents of the system info stream here. This would also be loosely related to #455, as it concerns itself with a way to confidently identify macOS minidumps via the CodeView record.

**Comment by relaxolotl** [comment]
Something that the minidumps have in common is that they're all coming from crashpad. The contents of the modules also share a quirk; Their CodeView records all look vaguely like the following:

```
  (code_file)                     = path to file
  (code_identifier)               = zeroed out on master right now
  (cv_record).cv_signature        = 0x53445352
  (cv_record).signature           = 00000000-0000-0000-0000-000000000000
  (cv_record).age                 = 0
  (cv_record).pdb_file_name       = same value as `code_file`
  (misc_record)                   = (null)
  (debug_file)                    = same value as `code_file`
  (debug_identifier)              = "00000000-0000-0000-0000-000000000000"
  (version)                       = "0.0.0.0"
```
This will be relevant a little later.

[It looks like when crashpad is unable to load the debug information for a module to populate its CodeView record with, it just writes an empty CodeView record.](https://chromium.googlesource.com/crashpad/crashpad/+/4860f64923df01fddc96803da3ffc14f47668d2a/snapshot/win/module_snapshot_win.cc#59) It also looks like it reuses the path to the module as the path to the PDB. In comparison, [breakpad calls out to `dbghelp.dll`'s `MinidumpWriteDump`](https://chromium.googlesource.com/breakpad/breakpad/+/42d24756174947921d282ee87e2b8e48f6eed3bf/src/client/windows/handler/exception_handler.cc#229) to create the minidump.

Anyways, the snippet right below the first paragraph is basically the empty-ish CodeView record that crashpad creates when it struggles with a module. Unfortunately it looks like I wasn't rigorous enough with my initial checks to make sure that crashpad also respected the `age = 0` "rule", which was a mistake on my part.

I'm under the impression that it would be quite difficult to change crashpad so it stops writing these, or to at least change their default value for a module's age when writing empty CodeViews. This leaves us with only really one solution, which is, I suppose the proper way of detecting a minidump's operating system: Threading the `MinidumpSystemInfo` into the `MinidumpModuleList` somehow.
