### ISSUE TITLE
Actually publish synth-minidump

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#496]
Apparently all the testing I did had a weird knock-on effect that synth-minidump is now in the lockfile as a dependency of minidump-stackwalk even though it's "only" a dev-dependency and `cargo publish` freaks out. To move the release along I just commented out that dep for the publish and reverted it in the post-release commit. 

In the future we should just actually publish synth-minidump.

Based on the new proposal of https://github.com/rust-lang/rfcs/pull/3243 we should probably rename it to minidump-synth or something so that our "namespacing" is consistent.

**Comment by luser** [comment]
That's annoying, it's not really useful to anyone else. :cry:
